# Numerical Python End to End in Detail

### Numpy:

Numpy- is a <b>Numerical Python</b>

It is developed by <b>Travis Oliphant in 2005</b>

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays

### Why:

Numpy is built using <b>python</b>, and most of the part which requires fatser execution is <b>developed using c or c++</b>,So it is very fast in execution.

Numpy arrays are called as <b>ndarray</b>

Numpy has 50x speed as compared to python list

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it <b>stores numpy arrays at one continuous location</b>

Numpy codes are available at:
https://github.com/numpy/numpy



## Installation of Numpy

In [45]:
import numpy as np

np.__version__

'1.18.5'

In [48]:
# create a numpy array using list
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)
print(type(arr))


lst = [10,20,30,40]

ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [52]:
# How to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)


# lets check the dimensions of the array

print("Number of dimensions: ",arr.ndim)

[1 2 3 4 5 6 7 8 9]
Number of dimensions:  1


In [57]:
# Create numpy array using tuple

tup = (1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))
print("Dimensions: ",ar.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
Dimensions:  1


In [ ]:
# Different Dimensional arrays:

In [59]:
# 0-D array

arr = np.array(200)

print(arr) 

# dimensions

print("Dimensions: ",arr.ndim)


200
Dimensions:  0


In [63]:
# 1-D array

arr = np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

# dimesnsions
print(arr.ndim)

# Access elements an 1-D array

print("Element present at 4th index: ",arr[4])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
Element present at 4th index:  5


In [64]:
# 2-D array
# Arrays ahaving 1-D array as input element, are called as 2-D array
ar = [[1,2,3],[4,5,6]]
arr = np.array(ar)
print(arr)
print("Dimensions: ",arr.ndim)

[[1 2 3]
 [4 5 6]]
Dimensions:  2


In [75]:
# Access the elements of 2-D array
#one way is to write

print(arr[0])
print(arr[0][2])
# another way is like
print(arr[1])
print(arr[1,1])

# dimensions

print("Dimensions: ",arr.ndim)

[1 2 3]
3
[4 5 6]
5
Dimensions:  2


In [77]:
# 3-D array
# array that has 2-D arrays (matrices) as its elements is 
# called 3-D array.
ar = [[[1, 2, 3], [4, 5, 6]] , [[10, 20, 30], [40, 50, 60]]]
print(type(ar))

arr = np.array(ar)
print(arr)
print(type(arr))
print("Dimensions:",arr.ndim)
# dimensions

print(arr.ndim)

<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
Dimensions: 3
3


In [88]:
# access the elements of the 3-D array
# One way is 

print(arr[1])
print(arr[0][0])
print(arr[0][0][2])

# Another way


print(arr[1])
print(arr[0,0])
print(arr[0,0,2])

[[10 20 30]
 [40 50 60]]
[1 2 3]
3
[[10 20 30]
 [40 50 60]]
[1 2 3]
3


In [89]:
# create an n dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5
