# Numerical Python End to End in Detail

### Numpy:

Numpy- is a <b>Numerical Python</b>

It is developed by <b>Travis Oliphant in 2005</b>

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays

### Why:

Numpy is built using <b>python</b>, and most of the part which requires fatser execution is <b>developed using c or c++</b>,So it is very fast in execution.

Numpy arrays are called as <b>ndarray</b>

Numpy has 50x speed as compared to python list

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it <b>stores numpy arrays at one continuous location</b>

Numpy codes are available at:
https://github.com/numpy/numpy



## Installation of Numpy

In [1]:
import numpy as np

np.__version__

'1.18.5'

In [2]:
# create a numpy array using list
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)
print(type(arr))


lst = [10,20,30,40]

ar = np.array(lst)
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [3]:
# How to access the element
# its 1-D array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)


# lets check the dimensions of the array

print("Number of dimensions: ",arr.ndim)

[1 2 3 4 5 6 7 8 9]
Number of dimensions:  1


In [4]:
# Create numpy array using tuple

tup = (1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(type(ar))
print("Dimensions: ",ar.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
Dimensions:  1


In [5]:
# Different Dimensional arrays:

In [6]:
# 0-D array

arr = np.array(200)

print(arr) 

# dimensions

print("Dimensions: ",arr.ndim)


200
Dimensions:  0


In [7]:
# 1-D array

arr = np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

# dimesnsions
print(arr.ndim)

# Access elements an 1-D array

print("Element present at 4th index: ",arr[4])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
Element present at 4th index:  5


In [8]:
# 2-D array
# Arrays ahaving 1-D array as input element, are called as 2-D array
ar = [[1,2,3],[4,5,6]]
arr = np.array(ar)
print(arr)
print("Dimensions: ",arr.ndim)

[[1 2 3]
 [4 5 6]]
Dimensions:  2


In [9]:
# Access the elements of 2-D array
#one way is to write

print(arr[0])
print(arr[0][2])
# another way is like
print(arr[1])
print(arr[1,1])

# dimensions

print("Dimensions: ",arr.ndim)

[1 2 3]
3
[4 5 6]
5
Dimensions:  2


In [10]:
# 3-D array
# array that has 2-D arrays (matrices) as its elements is 
# called 3-D array.
ar = [[[1, 2, 3], [4, 5, 6]] , [[10, 20, 30], [40, 50, 60]]]
print(type(ar))

arr = np.array(ar)
print(arr)
print(type(arr))
print("Dimensions:",arr.ndim)
# dimensions

print(arr.ndim)

<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>
Dimensions: 3
3


In [11]:
# access the elements of the 3-D array
# One way is 

print(arr[1])
print(arr[0][0])
print(arr[0][0][2])

# Another way


print(arr[1])
print(arr[0,0])
print(arr[0,0,2])

[[10 20 30]
 [40 50 60]]
[1 2 3]
3
[[10 20 30]
 [40 50 60]]
[1 2 3]
3


In [12]:
# create an n dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Array Slicing

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

# Slice
print("Length: ",len(arr))
print(arr[0:9])

# [start:end], start included, end excluded

[1 2 3 4 5 6 7 8 9]
Length:  9
[1 2 3 4 5 6 7 8 9]


In [14]:
print(arr[0:5])


[1 2 3 4 5]


In [15]:
print(arr[4:])

[5 6 7 8 9]


## Negative Indices

In [16]:
print(arr)
print(arr[-1])

print(arr[-9])

[1 2 3 4 5 6 7 8 9]
9
1


In [17]:
print(arr[-3:-7])

[]


In [18]:
# Step value in slicing a Numpy array
print(arr)
print(arr[0:9:2]) 

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [19]:

print(arr[::2]) 

print(arr[0:6:2])

[1 3 5 7 9]
[1 3 5]


### Slicing of 2_D Array

In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#print(arr)
print("\n")

print(arr[1])
print(arr[1,2])

print(arr[0,1:4 ])

# arr[2_d array loc, range of elements]


#print(arr[0, 1:4]) 



[ 6  7  8  9 10]
8
[2 3 4]


In [21]:
print(arr)
print(arr[0:2,0:3])

#print(arr[0:2, 2]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [6 7 8]]


In [22]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15
(3, 5)


In [23]:
# 2, 3
# 20,30

print(arr[0:2,1:3])


# 20 30 40
# 22 33 44

print("\n",arr[1:3,1:4])

# Assignment: Do the slicing of 3_D array.



[[ 2  3]
 [20 30]]

 [[20 30 40]
 [22 33 44]]


## Data Types in NumPy

In [24]:
# dtype
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype) 

[1 2 3 4]
int64


In [25]:

arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(arr.dtype) 

['apple' 'banana' 'cherry']
<U6


In [26]:
# Creating Arrays With a Defined Data Type

arr = np.array([1,2,3,4],dtype='int')

print(arr)
print(arr.dtype)


arr = np.array([1,2,3,4,5,6],dtype='float')
print(arr)
print(arr.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4. 5. 6.]
float64


In [27]:
# int with 4 bytes
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


In [28]:
# Errors

#arr = np.array(['a', '2', '3'], dtype='i') 
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### Data Type Conversion

In [29]:
# float to int
arr = np.array([1.1,2.2,3.3,4.4])

newarr = arr.astype('int')

#newarr = arr.astype('i')
print(arr)
print(newarr)
print(newarr.dtype) 

[1.1 2.2 3.3 4.4]
[1 2 3 4]
int64


In [30]:
# int to bool

arr = np.array([1,2,5.5,0])

newarr = arr.astype('bool')
print(arr)
print(newarr)
print(newarr.dtype) 

[1.  2.  5.5 0. ]
[ True  True  True False]
bool


#### Difference Between Copy and View

In [31]:
# Copy: It is goint to create new instance for your values

arr = np.array([1,2,3,4,5,6])
x = arr.copy()
print(x)
x[0] = 100
print(x)


print(arr)
#print(x) 

[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [32]:
# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 200
print(arr)
print(x) 

[200   2   3   4   5]
[200   2   3   4   5]


In [33]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
#print(y.base)  

None


### Numpy Array Reshaping

In [34]:
# One-D array to 2-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr.size)
print(arr.shape)

newarr = arr.reshape(4, 3)
newarr1 = arr.reshape(12, 1)
newarr2 = arr.reshape(3, 4)
newarr3 = arr.reshape(6, 2)

print(newarr) 
print(newarr1)
print(newarr2)
print(newarr3)


# Create a 2d array and then conveet it into 1-D array

12
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [35]:
# 1-D array into 3-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 2, 2)
newarr1 = arr.reshape(2, 3, 2)
newarr2 = arr.reshape(2, 3, 2)


print(newarr)
print(newarr1)
print(newarr2)


# convert 3-D array into 1-D array

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Unknown Dimension

In [36]:
# If user dont know any one dimension out 3 dimensions then 
# numpy can obtain it for user. User have mension the -1 for that dim.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening an arrays

In [37]:
# if u want to obtain a 1-D array using N-D array then reshape(-1)
arr = np.array([[10,20,30],[40,50,60]])

print(arr)
print(arr.shape)
newarr = arr.reshape(-1)
print(newarr.shape)
print(newarr) 

[[10 20 30]
 [40 50 60]]
(2, 3)
(6,)
[10 20 30 40 50 60]


## NumPy Array Iterating

In [38]:
# Iterating: means that you going through each element of that array
arr = np.array([1, 2, 3])

for x in arr:
  print(x) 

1
2
3


In [39]:
# iterating on 2-D array 
arr = np.array([[1,2,3],[10,20,30]])

print(arr)

for x in arr:
    print(x)
    

[[ 1  2  3]
 [10 20 30]]
[1 2 3]
[10 20 30]


In [40]:
# Iterating on scalar element of 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)
    for y in x:
        print(y)


[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [41]:
# on 3 D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)
print("\n\n")
for x in arr:
    print(x,"\n")
    for y in x:
        print(y,"\n")
        for z in y:
            print(z,"\n")
        

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



[[1 2 3]
 [4 5 6]] 

[1 2 3] 

1 

2 

3 

[4 5 6] 

4 

5 

6 

[[ 7  8  9]
 [10 11 12]] 

[7 8 9] 

7 

8 

9 

[10 11 12] 

10 

11 

12 



In [42]:
# Interating on each element of array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z) 

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()

In [43]:
# Itearting on 3-D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

y = np.nditer(arr)

for x in y:
    print(x)

1
2
3
4
5
6
7
8


In [44]:
# casting array elements from one type to other data type

arr = np.array([1, 2, 3])

for x in np.nditer(arr,flags= ['buffered'], op_dtypes = ['float']):
    print(x)

for x in np.nditer(arr,flags= ['buffered'], op_dtypes = ['U']):
    print(x)
    
for x in np.nditer(arr,flags= ['buffered'], op_dtypes = ['S']):
    print(x)

1.0
2.0
3.0
1
2
3
b'1'
b'2'
b'3'


In [45]:
# Slicing of an numpy array and steps in iterations
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x) 

1
3
5
7


### Iteration Using ndenumerate()

In [46]:
# Enumeration means mentioning sequence number of somethings
# one by one.
arr = np.array([1, 2, 3])

for id, x in np.ndenumerate(arr):
    print(id,x)
    

(0,) 1
(1,) 2
(2,) 3


In [47]:
# on 2-D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)
    

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Joining Array

In [48]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 


[1 2 3 4 5 6]


In [49]:
# Array Concatenation using axis option

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5,6 ], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Joining Arrays Using Stack Functions


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

arr = np.stack((arr1, arr2), axis=0)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [51]:
# hstack function
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [52]:
# stacking along the columns
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [53]:
# stacking along depth
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


### Splitting Array

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
newarr = np.split(arr, 3)
print(newarr)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [55]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
newarr = np.split(arr, 3, axis = 1)
print(newarr)

for i in newarr:
    print(i)

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
newarr = np.split(arr, 3)
# newarr = np.split(arr, 4) # This will raise an Value Error
print(newarr)

for i in newarr:
    print(i)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [57]:
# IF no_of elements are less then it adjust in last array
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 5)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[5 6]


In [59]:
# Array splitting on 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4, axis = 0)

for i in newarr:
    print(i,"\n") 
print("\n\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]] 

[[11 12]] 






In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], 
                [13, 14, 15], [16, 17, 18]])
print(arr.shape)
newarr = np.array_split(arr, 3)

print(newarr) 

(6, 3)
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [61]:
# Array splitting on axis
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr) 
#newarr = np.array_split(arr, 3, axis=0)

#print(newarr) 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### using hsplit() opposite of hstack()

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching Arrays

In [63]:
# finding element in 1-D
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 5)

print(arr)
print("Location : ",x)

[1 2 3 4 5 4 4]
Location :  (array([4]),)


In [64]:
# Arithmetic operations on numpy array

ar = np.array([[1,2,3],[4,5,6]])
print(ar)

print("\nAddition:\n",ar+1)

print("\n Substraction:\n",ar-1)

print("\n Mult:\n",ar*2)

print("\n Division:\n",ar/0.5)

[[1 2 3]
 [4 5 6]]

Addition:
 [[2 3 4]
 [5 6 7]]

 Substraction:
 [[0 1 2]
 [3 4 5]]

 Mult:
 [[ 2  4  6]
 [ 8 10 12]]

 Division:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [65]:
# find the location even number in my numpy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7]),)


In [66]:
# find the locations of even number in numpy array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

loc = np.where(arr%2 == 1)

print("Locations:", loc)

Locations: (array([0, 2, 4, 6]),)


In [67]:
## searchsorted()

# performs a binary search in the array, and returns the index 
# where the specified value would be inserted to maintain 
# the search order.

# this method does not insert element , 
# it just returns a location for element in the numpy array
arr = np.array([6, 7, 8, 9])

loc = np.searchsorted(arr, 7, side='left')
print(arr)
print("Location where element to be inserted:",loc)

[6 7 8 9]
Location where element to be inserted: 1


In [68]:
## Side


loc = np.searchsorted(arr, 8.5, side='right')

print(arr)

print("Location where element to be inserted:",loc)

[6 7 8 9]
Location where element to be inserted: 3


In [69]:
### Multiple Values

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]


#### Sorting Arrays


Sorting means putting elements in an ordered sequence.
like numeric or alphabetical, ascending or descending.


sort(), that will sort a specified array.

In [70]:
# sort() on numerical arrays
arr = np.array([3, 2, 0, 1])

res = np.sort(arr)

print(arr)

print(res)

[3 2 0 1]
[0 1 2 3]


In [71]:
# sort() on string array
arr = np.array(['banana', 'cherry', 'apple'])

res = np.sort(arr)

print(arr)

print(res)

['banana' 'cherry' 'apple']
['apple' 'banana' 'cherry']


In [72]:
# sort() boolean values
arr = np.array([True, False, True])


res = np.sort(arr)

print(arr)

print(res)


[ True False  True]
[False  True  True]


In [73]:
## sort() on 2-D Array


arr = np.array([[3, 2, 4], [5, 0, 1]])

print(arr)

res = np.sort(arr)

print("\n",res)


# work on axis=0
print("Sorting on 0 axis:\n",arr)

res = np.sort(arr, axis=0)

print("\n",res)

print("Sorting on 1 axis:\n",arr)

res = np.sort(arr, axis=1)

print("\n",res)

[[3 2 4]
 [5 0 1]]

 [[2 3 4]
 [0 1 5]]
Sorting on 0 axis:
 [[3 2 4]
 [5 0 1]]

 [[3 0 1]
 [5 2 4]]
Sorting on 1 axis:
 [[3 2 4]
 [5 0 1]]

 [[2 3 4]
 [0 1 5]]


### Filter Array


Getting some elements out of an existing array and creating a new array out of them is called filtering.

NumPy filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.



In [126]:
arr = np.array([1,2,3,4,5])

x = [True, False, False, False, True]

newarr = arr[x]

print(arr)
print(newarr)


[1 2 3 4 5]
[1 5]


In [128]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)
# Create an empty list
index = []

# go through each element in arr
for i in arr:
    
  # if the element is higher than 4, set the value to True, otherwise False:
    if i > 4:
        index.append(True)
    else:
        index.append(False)

print(index)

newarr = arr[index]

print(newarr)
    
  


[1 2 3 4 5 6 7 8 9]
[False, False, False, False, True, True, True, True, True]
[5 6 7 8 9]


In [131]:
# print a list of even number from original list using array filter

print(arr)

index = []

# i % 2 == 0

for i in arr:
    if i % 2 == 0:
        index.append(True)
    else:
        index.append(False)

print(index)

newarr = arr[index]

print(newarr)

[1 2 3 4 5 6 7 8 9]
[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [132]:

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False False  True  True]
[43 44]


In [133]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False  True False  True False  True False]
[2 4 6]


### Other Numpy Functions

In [139]:
arr = np.arange(25)
print(arr)
print(type(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
<class 'numpy.ndarray'>


In [140]:
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [150]:
# convert to 2-d
arr_2d = np.reshape(arr,(5,5))
print(arr_2d)
print(arr_2d.shape)
# other way
arr2 = arr.reshape(5,5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [151]:
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [152]:
arr_2d.min()

0

In [153]:
arr_2d.max()

24

In [154]:
arr_2d.argmax()

24

In [155]:
# indices to sort array
arr_2d.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [156]:
arr_2d.diagonal()

array([ 0,  6, 12, 18, 24])

In [157]:
arr_2d.sum()

300

In [158]:
arr_2d.mean()

12.0

In [159]:
# returns the indices of non-zero element
print(arr_2d)
arr_2d.nonzero()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4]))

In [171]:
# create array of 10 element between start and end values
ar2 = np.linspace(10,25, 10)

In [172]:
ar2

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        , 21.66666667, 23.33333333, 25.        ])

In [173]:
# flatten array
print(arr_2d)
arr_2d.ravel()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [174]:
# create array with random elements
ar = np.random.randn(3,3)

In [175]:
ar

array([[ 1.28062653, -0.36964693, -0.25839626],
       [-0.52661285, -0.7540983 , -0.44352622],
       [-0.285323  ,  0.30412223, -2.37738857]])

In [180]:
# unit matrix
ar = np.eye(4,4)
print(ar)
ar3 = np.eye(5,5, 2)

ar3

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [181]:
ar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [183]:
ar = np.ones((2,3))

In [184]:
ar

array([[1., 1., 1.],
       [1., 1., 1.]])

In [185]:
ar4 = np.diag([2,2,2,2])

In [186]:
ar4

array([[2, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])

In [187]:
ar4 = np.diag([1,2,3,4])

In [188]:
ar4

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [193]:
ar1 = np.arange(1,5)
ar2 = np.arange(1,5)

In [194]:
print(ar1)
print(ar2)

[1 2 3 4]
[1 2 3 4]


In [195]:
ar_1 = ar1.reshape(2,2)
ar_2 = ar2.reshape(2,2)

In [196]:
print(ar_1)
print(ar_2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [197]:
ar_1.dot(ar_2)

array([[ 7, 10],
       [15, 22]])

In [198]:
ar_1 * 2

array([[2, 4],
       [6, 8]])